config/routes.rb
Twitr::Application.routes.draw do
  root 'tweeds#index'

  get '/tweeds' => 'tweeds#index'
  get '/tweeds/new' => 'tweeds#new'
  get '/tweeds/:id' => 'tweeds#show'
  get '/tweeds/:id/edit' => 'tweeds#edit'
  delete '/tweeds/:id' => 'tweeds#destroy'
  post '/tweeds/' => 'tweeds#create'
  put '/tweeds/:id' => 'tweeds#update'

  get '/creators' => 'creators#index'
  get '/creators/new' => 'creators#new'
  get '/creators/:id' => 'creators#show'
  get '/creators/:id/edit' => 'creators#edit'
  delete '/creators/:id' => 'creators#destroy'
  post '/creators/' => 'creators#create'
  put '/creators/:id' => 'creators#update'
end

app/models/creator.rb
# == Schema Information
#
# Table name: creators
#
#  id         :integer          not null, primary key
#  username   :string(255)
#  email      :string(255)
#  phone      :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Creator < ActiveRecord::Base
	has_many :tweeds
end

app/models/tweed.rb
# == Schema Information
#
# Table name: tweeds
#
#  id         :integer          not null, primary key
#  creator_id :integer
#  content    :text
#  created_at :datetime
#  updated_at :datetime
#

class Tweed < ActiveRecord::Base
	belongs_to :creator
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/creators_controller.rb
class CreatorsController < ApplicationController
  before_action :set_creator, only: [:show, :edit, :update, :destroy]

  # GET /creators
  # GET /creators.json
  def index
    @creators = Creator.all
  end

  # GET /creators/1
  # GET /creators/1.json
  def show
  end

  # GET /creators/new
  def new
    @creator = Creator.new
  end

  # GET /creators/1/edit
  def edit
    @creator = Creator.find(params[:id])
  end

  # POST /creators
  # POST /creators.json
  def create
    @creator = Creator.new(creator_params)

    respond_to do |format|
      if @creator.save
        format.html { redirect_to creators_path, notice: 'Creator was successfully created.' }
        format.json { render action: 'show', status: :created, location: @creator }
      else
        format.html { render action: 'new' }
        format.json { render json: @creator.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /creators/1
  # PATCH/PUT /creators/1.json
  def update
    respond_to do |format|
      if @creator.update(creator_params)
        format.html { redirect_to creators_path, notice: 'Creator was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @creator.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /creators/1
  # DELETE /creators/1.json
  def destroy
    @creator.destroy
    respond_to do |format|
      format.html { redirect_to creators_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_creator
      @creator = Creator.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def creator_params
      params.require(:creator).permit(:username, :email, :phone)
    end
end

app/controllers/tweeds_controller.rb
class TweedsController < ApplicationController
  before_action :set_tweed, only: [:show, :edit, :update, :destroy]

  # GET /tweeds
  # GET /tweeds.json
  def index
    @tweeds = Tweed.all
  end

  # GET /tweeds/1
  # GET /tweeds/1.json
  def show
  end

  # GET /tweeds/new
  def new
    @tweed = Tweed.new
  end

  # GET /tweeds/1/edit
  def edit
    @tweed = Tweed.find(params[:id])
  end

  # POST /tweeds
  # POST /tweeds.json
  def create
    @tweed = Tweed.new(tweed_params)

    respond_to do |format|
      if @tweed.save
        format.html { redirect_to root_path, notice: 'Tweed was successfully created.' }
        format.json { render action: 'show', status: :created, location: @tweed }
      else
        format.html { render action: 'new' }
        format.json { render json: @tweed.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweeds/1
  # PATCH/PUT /tweeds/1.json
  def update
    respond_to do |format|
      if @tweed.update(tweed_params)
        format.html { redirect_to root_path, notice: 'Tweed was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @tweed.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweeds/1
  # DELETE /tweeds/1.json
  def destroy
    @tweed = Tweed.find(params[:id])
    @tweed.destroy
    respond_to do |format|
      format.html { redirect_to root_path }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweed
      @tweed = Tweed.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tweed_params
      params.require(:tweed).permit(:creator_id, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/creators_helper.rb
module CreatorsHelper
end

app/helpers/tweeds_helper.rb
module TweedsHelper
end

app/views/creators/_form.html.erb
<%= form_for(@creator) do |f| %>
  <% if @creator.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@creator.errors.count, "error") %> prohibited this creator from being saved:</h2>

      <ul>
      <% @creator.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :username %><br>
    <%= f.text_field :username, class: 'form-control', placeholder: 'Username', autofocus: true %>
  </div>
  <div class="form-group">
    <%= f.label :email %><br>
    <%= f.text_field :email, class: 'form-control', placeholder: 'Email' %>
  </div>
  <div class="form-group">
    <%= f.label :phone %><br>
    <%= f.text_field :phone, class: 'form-control', placeholder: 'Phone' %>
  </div>
  <div class="actions">
    <%= f.submit :Save, class: 'btn btn-primary' %>
    <%= link_to 'Back', creators_path, class: 'btn btn-default' %>
  </div>
<% end %>

app/views/creators/edit.html.erb
<h1>Editing creator</h1>

<%= form_for(@creator, url: "/creators/#{@creator.id}", method: :put) do |f| %>
  <% if @creator.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@creator.errors.count, "error") %> prohibited this creator from being saved:</h2>

      <ul>
      <% @creator.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :username %><br>
    <%= f.text_field :username, class: 'form-control', placeholder: 'Username', autofocus: true %>
  </div>
  <div class="form-group">
    <%= f.label :email %><br>
    <%= f.text_field :email, class: 'form-control', placeholder: 'Email' %>
  </div>
  <div class="form-group">
    <%= f.label :phone %><br>
    <%= f.text_field :phone, class: 'form-control', placeholder: 'Phone' %>
  </div>
  <div class="actions">
    <%= f.submit :Save, class: 'btn btn-primary' %>
    <%= link_to 'Back', creators_path, class: 'btn btn-default' %>
  </div>
<% end %>

app/views/creators/index.html.erb
<strong>Listing creators</strong>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Action</th>
    </tr>
  </thead>

  <tbody>
    <% @creators.each do |creator| %>
      <tr>
        <td><%= creator.username %></td>
        <td><%= creator.email %></td>
        <td><%= creator.phone %></td>
        <td><%= link_to 'Edit', "/creators/#{creator.id}/edit" %>
        | <%= link_to 'Destroy', "/creators/#{creator.id}", method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Creator', creators_new_path %>

app/views/creators/new.html.erb
<h2>New creator</h2>

<%= render 'form' %>

app/views/creators/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @creator.username %>
</p>

<p>
  <strong>Email:</strong>
  <%= @creator.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @creator.phone %>
</p>

<%= link_to 'Edit', edit_creator_path(@creator) %> |
<%= link_to 'Back', creators_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Twitr</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="container">
		<%= render "/shared/header" %>
		<%= yield %>
		<%= render "/shared/footer" %>
	</div>
</body>
</html>

app/views/shared/_footer.html.erb
<div class="footer">
	<p>© Company 2014</p>
</div>

app/views/shared/_header.html.erb
  <div class="header">
    <ul class="nav nav-pills pull-right">
      <li class="active"><a href="#"><span class='glyphicon glyphicon-home'></span></a></li>
      <li><a href="/tweeds/new"><span class='glyphicon glyphicon-comment'></span></a></li>
      <li><a href="/creators"><span class='glyphicon glyphicon-user'></span></a></li>
    </ul>
    <h3 class="text-muted">Tweed</h3>
  </div>

app/views/tweeds/_form.html.erb
<%= form_for(@tweed) do |f| %>
  <% if @tweed.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tweed.errors.count, "error") %> prohibited this tweed from being saved:</h2>

      <ul>
      <% @tweed.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :creator_id %><br>
    <%= f.select :creator_id, options_for_select(Creator.all.map {|c| [c.username, c.id] }), {prompt: 'Select Creator'}, {required: true, class: 'form-control'} %>
  </div>
  <div class="form-group">
    <%= f.label :content %><br>
    <%= f.text_area :content, class: 'form-control', rows: 10, required: true, placeholder: 'Type your content here..,' %>
  </div>
  <div class="actions">
    <%= f.submit :Save, class: 'btn btn-primary' %>
    <%= link_to 'Back', root_path, class: 'btn btn-default' %>
  </div>
<% end %>

app/views/tweeds/edit.html.erb
<h1>Editing tweed</h1>

<%= form_for(@tweed, url: "/tweeds/#{@tweed.id}", method: :put) do |f| %>
  <% if @tweed.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tweed.errors.count, "error") %> prohibited this tweed from being saved:</h2>

      <ul>
      <% @tweed.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :creator_id %><br>
    <%= f.select :creator_id, options_for_select(Creator.all.map {|c| [c.username, c.id] }), {prompt: 'Select Creator'}, {required: true, class: 'form-control'} %>
  </div>
  <div class="form-group">
    <%= f.label :content %><br>
    <%= f.text_area :content, class: 'form-control', rows: 10, required: true, placeholder: 'Type your content here..,' %>
  </div>
  <div class="actions">
    <%= f.submit :Save, class: 'btn btn-primary' %>
    <%= link_to 'Back', root_path, class: 'btn btn-default' %>
  </div>
<% end %>


<%= link_to 'Back', tweeds_path %>

app/views/tweeds/index.html.erb
<% @tweeds.each do |tweed| %>

  <div class="jumbotron">
    <h2><%= tweed.creator.username %></h2>
    <p class="lead"><%= tweed.content.html_safe rescue '' %></p>
    <div class="time pull-left"><%= tweed.created_at.strftime("%d-%M %Y") %></div>
    <div class="time pull-right"><%= link_to "<span class='glyphicon glyphicon-pencil'></span> Edit".html_safe, "/tweeds/#{tweed.id}/edit" %> | <%= link_to "<span class='glyphicon glyphicon-remove-sign'></span> Remove".html_safe, "/tweeds/#{tweed.id}", method: :delete, confirm: 'Do you want to remove?' %></div>
  </div>

<% end %>

app/views/tweeds/index1.html.erb
<h1>Listing tweeds</h1>

<table>
  <thead>
    <tr>
      <th>Creator</th>
      <th>Content</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @tweeds.each do |tweed| %>
      <tr>
        <td><%= tweed.creator_id %></td>
        <td><%= tweed.content %></td>
        <td><%= link_to 'Show', tweed %></td>
        <td><%= link_to 'Edit', edit_tweed_path(tweed) %></td>
        <td><%= link_to 'Destroy', tweed, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tweed', new_tweed_path %>

app/views/tweeds/new.html.erb
<h1>New tweed</h1>

<%= render 'form' %>

app/views/tweeds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Creator:</strong>
  <%= @tweed.creator_id %>
</p>

<p>
  <strong>Content:</strong>
  <%= @tweed.content %>
</p>

<%= link_to 'Edit', edit_tweed_path(@tweed) %> |
<%= link_to 'Back', tweeds_path %>